name: C/C++ CI build release for tag

on:
  push:
    tags:        
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: adding apt key for repo below
      run: sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
    - name: add wxwidgets unofficial repo
      run: sudo apt-add-repository 'deb https://repos.codelite.org/wx3.2.0/ubuntu/ jammy universe'
    - name: update apt
      run: sudo apt-get update
    - name: install libraries
      run: sudo apt-get install libzip-dev libnotify4 libwxbase3.2-0-unofficial libwxbase3.2unofficial-dev libwxgtk3.2-0-unofficial libwxgtk3.2unofficial-dev wx3.2-headers wx-common libwxgtk-media3.2-0-unofficial libwxgtk-media3.2unofficial-dev libwxgtk-webview3.2-0-unofficial libwxgtk-webview3.2unofficial-dev libwxgtk-webview3.2-0-unofficial-dbg libwxbase3.2-0-unofficial-dbg libwxgtk3.2-0-unofficial-dbg libwxgtk-media3.2-0-unofficial-dbg wx3.2-i18n wx3.2-examples
    - name: make
      run: make
    - name: make install
      run: make install
    - name: Prepare archive
      run: cd install && tar -czf FlexArch-linux.tar.gz *
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: test export
      run: export
    - name: create release
      uses: ncipollo/release-action@v1.13.0
      with:
          artifacts: "install/FlexArch-linux.tar.gz"
          draft: false
          prerelease: true
