name: C/C++ CI commit check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: adding apt key for repo below
      run: sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
    - name: add wxwidgets unofficial repo
      run: sudo apt-add-repository 'deb https://repos.codelite.org/wx3.2.0/ubuntu/ jammy universe'
    - name: update apt
      run: sudo apt-get update
    - name: install libraries
      run: sudo apt-get install libzip-dev libnotify4 libwxbase3.2-0-unofficial libwxbase3.2unofficial-dev libwxgtk3.2-0-unofficial libwxgtk3.2unofficial-dev wx3.2-headers wx-common libwxgtk-media3.2-0-unofficial libwxgtk-media3.2unofficial-dev libwxgtk-webview3.2-0-unofficial libwxgtk-webview3.2unofficial-dev libwxgtk-webview3.2-0-unofficial-dbg libwxbase3.2-0-unofficial-dbg libwxgtk3.2-0-unofficial-dbg libwxgtk-media3.2-0-unofficial-dbg wx3.2-i18n wx3.2-examples
    - name: make
      run: make
