name: C/C++ CI commit check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: adding apt key for repo below
      run: sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
    - name: add wxwidgets unofficial repo
      run: sudo apt-add-repository 'deb https://repos.codelite.org/wx3.2.0/ubuntu/ jammy universe'
    - name: update apt
      run: sudo apt-get update
    - name: install libraries
      run: sudo apt-get install libssl-dev libbz2-dev libzstd-dev libnotify4 libwxbase3.2-0-unofficial libwxbase3.2unofficial-dev libwxgtk3.2-0-unofficial libwxgtk3.2unofficial-dev wx3.2-headers wx-common libwxgtk-media3.2-0-unofficial libwxgtk-media3.2unofficial-dev libwxgtk-webview3.2-0-unofficial libwxgtk-webview3.2unofficial-dev libwxgtk-webview3.2-0-unofficial-dbg libwxbase3.2-0-unofficial-dbg libwxgtk3.2-0-unofficial-dbg libwxgtk-media3.2-0-unofficial-dbg wx3.2-i18n wx3.2-examples libgtk-3-0 libgtk-3-dev
    - name: download recent libzip
      run: wget https://libzip.org/download/libzip-1.10.1.tar.xz
    - name: unpack libzip
      run: tar -vxJf libzip-1.10.1.tar.xz
    - name: prepare libzip build
      working-directory: libzip-1.10.1
      run: cmake .
    - name: build & install libzip
      working-directory: libzip-1.10.1
      run: sudo make install
    - name: make flexarch
      run: make
